"""
Property of BeeHex, LLC
All rights reserved.
Developer: Bart Chou
"""



from PyQt5 import QtCore, QtGui, QtWidgets

male = True
female = False
height_feet = "Select a Number"
height_inch = "Select a Number"
weight = 150
body_fat = 15
age = "Select a Number"
purpose = "Select a Type"
min = 30
heart_rate = 70
intensity = "Select a Number"
leanfactor_string = "Select a Number (determined by body fat %)"
fitness_string = "What are your fitness goal?"
exercise_string = "What type of exercise?"

def bmr_male(weight, feet, inches, age):  # p = pound, h_f = height in feet, h_i = height in inches, y = age
    temp = feet * 12 + inches
    result = 66 + 6.23 * weight + 12.7 * temp - 6.8 * age
    return round(result)


def bmr_female(weight, feet, inches, age):
    temp = feet * 12 + inches
    result = 655 + 4.35 * weight + 4.7 * temp - 4.7 * age
    return round(result)

def get_lbm(weight, body_fat):
    fat = body_fat * 0.01
    result = (1 - fat) * weight
    return round(result)

def get_leanfactor(leanfactor_string):
    lean_index = int(leanfactor_string[0])
    # lean index 1: multiplier is 1
    # lean index 2: multiplier is 0.95
    # lean index 3: multiplier is 0.90
    # lean index 4: multiplier is 0.85
    switcher = {1: 1,
                2: 0.95,
                3: 0.9,
                4: 0.85}
    return switcher.get(lean_index)

def get_proteinfactor(fitness_string, exercise_string):
    key_index = fitness_string[0] + exercise_string[0]
    switcher = {"1a": 0.6, "1b": 0.7, "1c": 0.8, "1d": 0.7,
                "2a": 0.7, "2b": 0.9, "2c": 0.9, "2d": 0.9,
                "3a": 0.8, "3b": 1.0, "3c": 1.6, "3d": 1.4,
                "4a": 0.8, "4b": 1.4, "4c": 1.8, "4d": 1.6}
    return switcher.get(key_index)

def calculate():
    global male, female, height_feet, height_inch, weight, body_fat
    global age, purpose, min, heart_rate, intensity, leanfactor_string
    global fitness_string, exercise_string
    # check if the program has all the required info to continue
    if (height_feet == "Select a Number" or
        height_inch == "Select a Number" or
        age == "Select a Number" or
        purpose == "Select a Type" or
        intensity == "Select a Number" or
        leanfactor_string == "Select a Number (determined by body fat %)" or
        fitness_string == "What are your fitness goal?" or
        exercise_string == "What type of exercise?"):

        ui.textBrowser_result.setText("fail to calculate. Make sure you have all the "
                                      "required number selected.")
        return None

    bmr = 0
    result = ""
    if male == True and female == False:
        result = result + "-"*13 + "given data" + "-"*13 + "\n" + \
                 "Gender: Male" + "\n"
        bmr = bmr_male(int(weight), int(height_feet), int(height_inch), int(age))

    elif male == False and female == True:
        result = result + "-"*13 + "given data" + "-"*13 + "\n" + \
                 "Gender: Female" + "\n"
        bmr = bmr_female(int(weight), int(height_feet), int(height_inch), int(age))

    leanfactor = get_leanfactor(leanfactor_string)
    proteinfactor = get_proteinfactor(fitness_string, exercise_string)
    lbm = get_lbm(int(weight), int(body_fat))

    result = result + \
             "Height: " + str(height_feet) + " feet  " + str(height_inch) + " inches" + "\n" + \
             "Weight: " + str(weight) + " pounds" + "\n" + \
             "Body fat: " + str(body_fat) + " %" + "\n" + \
             "Age: " + str(age) + "\n" + \
             "Purpose: " + purpose + "\n" + \
             "Physical activity rating: " + str(round(int(min) * float(intensity))) + "\n" + \
             "Heart rate: " + str(heart_rate) + "\n" + \
             "Lean factor: " + str(leanfactor) + "\n" + \
             "-"*12 + "the analysis" + "-"*12 + "\n" + \
             "BMR: " + str(bmr) + "\n" + \
             "Cals per day: " + str(round(bmr * leanfactor)) + "\n" + \
             "Cals per hour: "+ str(round(bmr * leanfactor * (1/24))) + "\n" + \
             "Protein per day: " + str(round(proteinfactor * lbm)) + " grams" + "\n"

    ui.textBrowser_result.setText(result)

def radioButton(task):
    global male, female
    if task == "male":
        male = ui.radioButton_male.isChecked()

    elif task == "female":
        female = ui.radioButton_female.isChecked()

def spin_box(task):
    global weight, min, heart_rate, body_fat
    if task == "weight":
        weight = ui.spinBox_weight.value()

    elif task == "min":
        min = ui.spinBox_min.value()

    elif task == "heart_rate":
        heart_rate = ui.spinBox_heartrate.value()

    elif task == "body_fat":
        body_fat = ui.spinBox_bodyfat.value()

def combo_box(task):
    global height_feet, height_inch, age, purpose, intensity, leanfactor_string, fitness_string, exercise_string
    if task == "feet":
        height_feet = ui.comboBox_feet.currentText()
    elif task == "inch":
        height_inch = ui.comboBox_inches.currentText()
    elif task == "age":
        age = ui.comboBox_age.currentText()
    elif task == "purpose":
        purpose = ui.comboBox_purpose.currentText()
    elif task == "intensity":
        intensity = ui.comboBox_intensity.currentText()
    elif task == "leanfactor":
        leanfactor_string = ui.comboBox_leanfactor.currentText()
    elif task == "fitness":
        fitness_string = ui.comboBox_fitnessgoal.currentText()
    elif task == "exercise":
        exercise_string = ui.comboBox_typeofexercise.currentText()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_allergies_after = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_allergies_after.setGeometry(QtCore.QRect(470, 341, 256, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_allergies_after.setFont(font)
        self.listWidget_allergies_after.setObjectName("listWidget_allergies_after")
        self.textBrowser_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_result.setGeometry(QtCore.QRect(20, 570, 341, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_result.setFont(font)
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(20, 520, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_calculate.setFont(font)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(200, 520, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 70, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(21, 71, 49, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_age = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_age.setGeometry(QtCore.QRect(110, 130, 142, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_age.setFont(font)
        self.comboBox_age.setObjectName("comboBox_age")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.comboBox_age.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 28, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 40, 29, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 40, 46, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 71, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.radioButton_female = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_female.setGeometry(QtCore.QRect(180, 10, 73, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_female.setFont(font)
        self.radioButton_female.setObjectName("radioButton_female")
        self.comboBox_feet = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_feet.setGeometry(QtCore.QRect(110, 40, 142, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_feet.setFont(font)
        self.comboBox_feet.setEditable(False)
        self.comboBox_feet.setObjectName("comboBox_feet")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.comboBox_feet.addItem("")
        self.radioButton_male = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_male.setGeometry(QtCore.QRect(110, 10, 55, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_male.setFont(font)
        self.radioButton_male.setChecked(True)
        self.radioButton_male.setObjectName("radioButton_male")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 130, 39, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 11, 51, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(21, 40, 46, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_inches = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_inches.setGeometry(QtCore.QRect(300, 40, 142, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_inches.setFont(font)
        self.comboBox_inches.setObjectName("comboBox_inches")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_inches.addItem("")
        self.comboBox_purpose = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_purpose.setGeometry(QtCore.QRect(110, 160, 120, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_purpose.setFont(font)
        self.comboBox_purpose.setObjectName("comboBox_purpose")
        self.comboBox_purpose.addItem("")
        self.comboBox_purpose.addItem("")
        self.comboBox_purpose.addItem("")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 340, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 250, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_leanfactor = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_leanfactor.setGeometry(QtCore.QRect(110, 250, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_leanfactor.setFont(font)
        self.comboBox_leanfactor.setObjectName("comboBox_leanfactor")
        self.comboBox_leanfactor.addItem("")
        self.comboBox_leanfactor.addItem("")
        self.comboBox_leanfactor.addItem("")
        self.comboBox_leanfactor.addItem("")
        self.comboBox_leanfactor.addItem("")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(500, 190, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 220, 74, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 190, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox_intensity = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_intensity.setGeometry(QtCore.QRect(360, 190, 133, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_intensity.setFont(font)
        self.comboBox_intensity.setObjectName("comboBox_intensity")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.comboBox_intensity.addItem("")
        self.listWidget_allergies_before = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_allergies_before.setGeometry(QtCore.QRect(110, 340, 251, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_allergies_before.setFont(font)
        self.listWidget_allergies_before.setObjectName("listWidget_allergies_before")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_allergies_before.addItem(item)
        self.pushButton_allergies_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_allergies_delete.setGeometry(QtCore.QRect(370, 370, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_allergies_delete.setFont(font)
        self.pushButton_allergies_delete.setObjectName("pushButton_allergies_delete")
        self.pushButton_allergies_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_allergies_add.setGeometry(QtCore.QRect(370, 340, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_allergies_add.setFont(font)
        self.pushButton_allergies_add.setObjectName("pushButton_allergies_add")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 190, 172, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spinBox_weight = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_weight.setGeometry(QtCore.QRect(110, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_weight.setFont(font)
        self.spinBox_weight.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_weight.setMinimum(1)
        self.spinBox_weight.setMaximum(999)
        self.spinBox_weight.setProperty("value", 150)
        self.spinBox_weight.setObjectName("spinBox_weight")
        self.spinBox_min = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_min.setGeometry(QtCore.QRect(110, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_min.setFont(font)
        self.spinBox_min.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_min.setKeyboardTracking(True)
        self.spinBox_min.setMinimum(1)
        self.spinBox_min.setMaximum(999)
        self.spinBox_min.setProperty("value", 30)
        self.spinBox_min.setObjectName("spinBox_min")
        self.spinBox_heartrate = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_heartrate.setGeometry(QtCore.QRect(110, 220, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_heartrate.setFont(font)
        self.spinBox_heartrate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_heartrate.setMinimum(1)
        self.spinBox_heartrate.setMaximum(999)
        self.spinBox_heartrate.setProperty("value", 70)
        self.spinBox_heartrate.setObjectName("spinBox_heartrate")
        self.spinBox_bodyfat = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_bodyfat.setGeometry(QtCore.QRect(110, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_bodyfat.setFont(font)
        self.spinBox_bodyfat.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_bodyfat.setMinimum(1)
        self.spinBox_bodyfat.setMaximum(99)
        self.spinBox_bodyfat.setProperty("value", 15)
        self.spinBox_bodyfat.setObjectName("spinBox_bodyfat")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(180, 100, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBox_fitnessgoal = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_fitnessgoal.setGeometry(QtCore.QRect(110, 280, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_fitnessgoal.setFont(font)
        self.comboBox_fitnessgoal.setObjectName("comboBox_fitnessgoal")
        self.comboBox_fitnessgoal.addItem("")
        self.comboBox_fitnessgoal.addItem("")
        self.comboBox_fitnessgoal.addItem("")
        self.comboBox_fitnessgoal.addItem("")
        self.comboBox_fitnessgoal.addItem("")
        self.comboBox_typeofexercise = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_typeofexercise.setGeometry(QtCore.QRect(110, 310, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_typeofexercise.setFont(font)
        self.comboBox_typeofexercise.setObjectName("comboBox_typeofexercise")
        self.comboBox_typeofexercise.addItem("")
        self.comboBox_typeofexercise.addItem("")
        self.comboBox_typeofexercise.addItem("")
        self.comboBox_typeofexercise.addItem("")
        self.comboBox_typeofexercise.addItem("")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(450, 650, 271, 191))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../../../../Users/nkbar/Desktop/Nutrients program/beehex_logo.png"))
        self.label_18.setObjectName("label_18")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.radioButton_male.toggled['bool'].connect(lambda: radioButton("male"))
        self.radioButton_female.toggled['bool'].connect(lambda: radioButton("female"))
        self.comboBox_feet.activated['QString'].connect(lambda: combo_box("feet"))
        self.comboBox_inches.activated['QString'].connect(lambda: combo_box("inch"))
        self.comboBox_age.activated['QString'].connect(lambda: combo_box("age"))
        self.comboBox_purpose.activated['QString'].connect(lambda: combo_box("purpose"))
        self.comboBox_intensity.activated['QString'].connect(lambda: combo_box("intensity"))
        self.comboBox_leanfactor.activated['QString'].connect(lambda: combo_box("leanfactor"))
        self.comboBox_fitnessgoal.activated['QString'].connect(lambda: combo_box("fitness"))
        self.comboBox_typeofexercise.activated['QString'].connect(lambda: combo_box("exercise"))
        self.spinBox_weight.editingFinished.connect(lambda: spin_box("weight"))
        self.spinBox_min.editingFinished.connect(lambda: spin_box("min"))
        self.spinBox_heartrate.editingFinished.connect(lambda: spin_box("heart_rate"))
        self.spinBox_bodyfat.editingFinished.connect(lambda: spin_box("body_fat"))
        self.pushButton_calculate.clicked.connect(calculate)
        self.pushButton_clear.clicked.connect(self.textBrowser_result.clear)
        # work on these later
        self.pushButton_allergies_add.clicked.connect(self.pushButton_allergies_add.show)
        self.pushButton_allergies_delete.clicked.connect(self.pushButton_allergies_delete.show)
        self.listWidget_allergies_before.itemClicked['QListWidgetItem*'].connect(self.pushButton_allergies_add.click)
        self.listWidget_allergies_after.itemClicked['QListWidgetItem*'].connect(self.listWidget_allergies_after.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Personalized Nutrition Analyzer"))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear the results"))
        self.label_6.setText(_translate("MainWindow", "Pounds"))
        self.label_5.setText(_translate("MainWindow", "Weight"))
        self.comboBox_age.setItemText(0, _translate("MainWindow", "Select a Number"))
        self.comboBox_age.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_age.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_age.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_age.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_age.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_age.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_age.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_age.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox_age.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox_age.setItemText(10, _translate("MainWindow", "10"))
        self.comboBox_age.setItemText(11, _translate("MainWindow", "11"))
        self.comboBox_age.setItemText(12, _translate("MainWindow", "12"))
        self.comboBox_age.setItemText(13, _translate("MainWindow", "13"))
        self.comboBox_age.setItemText(14, _translate("MainWindow", "14"))
        self.comboBox_age.setItemText(15, _translate("MainWindow", "15"))
        self.comboBox_age.setItemText(16, _translate("MainWindow", "16"))
        self.comboBox_age.setItemText(17, _translate("MainWindow", "17"))
        self.comboBox_age.setItemText(18, _translate("MainWindow", "18"))
        self.comboBox_age.setItemText(19, _translate("MainWindow", "19"))
        self.comboBox_age.setItemText(20, _translate("MainWindow", "20"))
        self.comboBox_age.setItemText(21, _translate("MainWindow", "21"))
        self.comboBox_age.setItemText(22, _translate("MainWindow", "22"))
        self.comboBox_age.setItemText(23, _translate("MainWindow", "23"))
        self.comboBox_age.setItemText(24, _translate("MainWindow", "24"))
        self.comboBox_age.setItemText(25, _translate("MainWindow", "25"))
        self.comboBox_age.setItemText(26, _translate("MainWindow", "26"))
        self.comboBox_age.setItemText(27, _translate("MainWindow", "27"))
        self.comboBox_age.setItemText(28, _translate("MainWindow", "28"))
        self.comboBox_age.setItemText(29, _translate("MainWindow", "29"))
        self.comboBox_age.setItemText(30, _translate("MainWindow", "30"))
        self.comboBox_age.setItemText(31, _translate("MainWindow", "31"))
        self.comboBox_age.setItemText(32, _translate("MainWindow", "32"))
        self.comboBox_age.setItemText(33, _translate("MainWindow", "33"))
        self.comboBox_age.setItemText(34, _translate("MainWindow", "34"))
        self.comboBox_age.setItemText(35, _translate("MainWindow", "35"))
        self.comboBox_age.setItemText(36, _translate("MainWindow", "36"))
        self.comboBox_age.setItemText(37, _translate("MainWindow", "37"))
        self.comboBox_age.setItemText(38, _translate("MainWindow", "38"))
        self.comboBox_age.setItemText(39, _translate("MainWindow", "39"))
        self.comboBox_age.setItemText(40, _translate("MainWindow", "40"))
        self.comboBox_age.setItemText(41, _translate("MainWindow", "41"))
        self.comboBox_age.setItemText(42, _translate("MainWindow", "42"))
        self.comboBox_age.setItemText(43, _translate("MainWindow", "43"))
        self.comboBox_age.setItemText(44, _translate("MainWindow", "44"))
        self.comboBox_age.setItemText(45, _translate("MainWindow", "45"))
        self.comboBox_age.setItemText(46, _translate("MainWindow", "46"))
        self.comboBox_age.setItemText(47, _translate("MainWindow", "47"))
        self.comboBox_age.setItemText(48, _translate("MainWindow", "48"))
        self.comboBox_age.setItemText(49, _translate("MainWindow", "49"))
        self.comboBox_age.setItemText(50, _translate("MainWindow", "50"))
        self.comboBox_age.setItemText(51, _translate("MainWindow", "51"))
        self.comboBox_age.setItemText(52, _translate("MainWindow", "52"))
        self.comboBox_age.setItemText(53, _translate("MainWindow", "53"))
        self.comboBox_age.setItemText(54, _translate("MainWindow", "54"))
        self.comboBox_age.setItemText(55, _translate("MainWindow", "55"))
        self.comboBox_age.setItemText(56, _translate("MainWindow", "56"))
        self.comboBox_age.setItemText(57, _translate("MainWindow", "57"))
        self.comboBox_age.setItemText(58, _translate("MainWindow", "58"))
        self.comboBox_age.setItemText(59, _translate("MainWindow", "59"))
        self.comboBox_age.setItemText(60, _translate("MainWindow", "60"))
        self.comboBox_age.setItemText(61, _translate("MainWindow", "61"))
        self.comboBox_age.setItemText(62, _translate("MainWindow", "62"))
        self.comboBox_age.setItemText(63, _translate("MainWindow", "63"))
        self.comboBox_age.setItemText(64, _translate("MainWindow", "64"))
        self.comboBox_age.setItemText(65, _translate("MainWindow", "65"))
        self.comboBox_age.setItemText(66, _translate("MainWindow", "66"))
        self.comboBox_age.setItemText(67, _translate("MainWindow", "67"))
        self.comboBox_age.setItemText(68, _translate("MainWindow", "68"))
        self.comboBox_age.setItemText(69, _translate("MainWindow", "69"))
        self.comboBox_age.setItemText(70, _translate("MainWindow", "70"))
        self.comboBox_age.setItemText(71, _translate("MainWindow", "71"))
        self.comboBox_age.setItemText(72, _translate("MainWindow", "72"))
        self.comboBox_age.setItemText(73, _translate("MainWindow", "73"))
        self.comboBox_age.setItemText(74, _translate("MainWindow", "74"))
        self.comboBox_age.setItemText(75, _translate("MainWindow", "75"))
        self.comboBox_age.setItemText(76, _translate("MainWindow", "76"))
        self.comboBox_age.setItemText(77, _translate("MainWindow", "77"))
        self.comboBox_age.setItemText(78, _translate("MainWindow", "78"))
        self.comboBox_age.setItemText(79, _translate("MainWindow", "79"))
        self.comboBox_age.setItemText(80, _translate("MainWindow", "80"))
        self.comboBox_age.setItemText(81, _translate("MainWindow", "81"))
        self.comboBox_age.setItemText(82, _translate("MainWindow", "82"))
        self.comboBox_age.setItemText(83, _translate("MainWindow", "83"))
        self.comboBox_age.setItemText(84, _translate("MainWindow", "84"))
        self.comboBox_age.setItemText(85, _translate("MainWindow", "85"))
        self.comboBox_age.setItemText(86, _translate("MainWindow", "86"))
        self.comboBox_age.setItemText(87, _translate("MainWindow", "87"))
        self.comboBox_age.setItemText(88, _translate("MainWindow", "88"))
        self.comboBox_age.setItemText(89, _translate("MainWindow", "89"))
        self.comboBox_age.setItemText(90, _translate("MainWindow", "90"))
        self.comboBox_age.setItemText(91, _translate("MainWindow", "91"))
        self.comboBox_age.setItemText(92, _translate("MainWindow", "92"))
        self.comboBox_age.setItemText(93, _translate("MainWindow", "93"))
        self.comboBox_age.setItemText(94, _translate("MainWindow", "94"))
        self.comboBox_age.setItemText(95, _translate("MainWindow", "95"))
        self.comboBox_age.setItemText(96, _translate("MainWindow", "96"))
        self.comboBox_age.setItemText(97, _translate("MainWindow", "97"))
        self.comboBox_age.setItemText(98, _translate("MainWindow", "98"))
        self.comboBox_age.setItemText(99, _translate("MainWindow", "99"))
        self.comboBox_age.setItemText(100, _translate("MainWindow", "100"))
        self.label_7.setText(_translate("MainWindow", "Age"))
        self.label_3.setText(_translate("MainWindow", "Feet"))
        self.label_4.setText(_translate("MainWindow", "Inches"))
        self.label_9.setToolTip(_translate("MainWindow", "Is this a meal?  Is this a snack? Etc."))
        self.label_9.setStatusTip(_translate("MainWindow", "Is this a meal?  Is this a snack? Etc."))
        self.label_9.setText(_translate("MainWindow", "Purpose*"))
        self.radioButton_female.setText(_translate("MainWindow", "Female"))
        self.comboBox_feet.setItemText(0, _translate("MainWindow", "Select a Number"))
        self.comboBox_feet.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_feet.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_feet.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_feet.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_feet.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_feet.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_feet.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_feet.setItemText(8, _translate("MainWindow", "8"))
        self.radioButton_male.setText(_translate("MainWindow", "Male"))
        self.label_8.setText(_translate("MainWindow", "Years"))
        self.label.setText(_translate("MainWindow", "Gender"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.comboBox_inches.setItemText(0, _translate("MainWindow", "Select a Number"))
        self.comboBox_inches.setItemText(1, _translate("MainWindow", "0"))
        self.comboBox_inches.setItemText(2, _translate("MainWindow", "1"))
        self.comboBox_inches.setItemText(3, _translate("MainWindow", "2"))
        self.comboBox_inches.setItemText(4, _translate("MainWindow", "3"))
        self.comboBox_inches.setItemText(5, _translate("MainWindow", "4"))
        self.comboBox_inches.setItemText(6, _translate("MainWindow", "5"))
        self.comboBox_inches.setItemText(7, _translate("MainWindow", "6"))
        self.comboBox_inches.setItemText(8, _translate("MainWindow", "7"))
        self.comboBox_inches.setItemText(9, _translate("MainWindow", "8"))
        self.comboBox_inches.setItemText(10, _translate("MainWindow", "9"))
        self.comboBox_inches.setItemText(11, _translate("MainWindow", "10"))
        self.comboBox_inches.setItemText(12, _translate("MainWindow", "11"))
        self.comboBox_purpose.setToolTip(_translate("MainWindow", "Is this a meal?  Is this a snack? Etc."))
        self.comboBox_purpose.setStatusTip(_translate("MainWindow", "Is this a meal?  Is this a snack? Etc."))
        self.comboBox_purpose.setItemText(0, _translate("MainWindow", "Select a Type"))
        self.comboBox_purpose.setItemText(1, _translate("MainWindow", "Meal"))
        self.comboBox_purpose.setItemText(2, _translate("MainWindow", "Snack"))
        self.label_15.setText(_translate("MainWindow", "Allergies"))
        self.label_13.setText(_translate("MainWindow", "Lean Factor"))
        self.comboBox_leanfactor.setItemText(0, _translate("MainWindow", "Select a Number (determined by body fat %)"))
        self.comboBox_leanfactor.setItemText(1, _translate("MainWindow", "1: (Lean) Men 10% to <14% - Women 14% to <18%"))
        self.comboBox_leanfactor.setItemText(2, _translate("MainWindow", "2: (Normal) Men 14% to <20% - Women 18% to <28%"))
        self.comboBox_leanfactor.setItemText(3, _translate("MainWindow", "3: (Clinically Obese) Men 20% to <28% - Women 28% to <38%"))
        self.comboBox_leanfactor.setItemText(4, _translate("MainWindow", "4: (Chronically Obese) Men over 28% - Women over 38%"))
        self.label_14.setText(_translate("MainWindow", "Intensity"))
        self.label_12.setText(_translate("MainWindow", "Heart Rate"))
        self.label_11.setToolTip(_translate("MainWindow", "Physical Activity Rating = # of minutes of exercise * intensity"))
        self.label_11.setStatusTip(_translate("MainWindow", "Physical Activity Rating = # of minutes of exercise * intensity"))
        self.label_11.setText(_translate("MainWindow", "PA Rating*"))
        self.comboBox_intensity.setItemText(0, _translate("MainWindow", "Select Intensity"))
        self.comboBox_intensity.setItemText(1, _translate("MainWindow", "0.1"))
        self.comboBox_intensity.setItemText(2, _translate("MainWindow", "0.2"))
        self.comboBox_intensity.setItemText(3, _translate("MainWindow", "0.3"))
        self.comboBox_intensity.setItemText(4, _translate("MainWindow", "0.4"))
        self.comboBox_intensity.setItemText(5, _translate("MainWindow", "0.5"))
        self.comboBox_intensity.setItemText(6, _translate("MainWindow", "0.6"))
        self.comboBox_intensity.setItemText(7, _translate("MainWindow", "0.7"))
        self.comboBox_intensity.setItemText(8, _translate("MainWindow", "0.8"))
        self.comboBox_intensity.setItemText(9, _translate("MainWindow", "0.9"))
        self.comboBox_intensity.setItemText(10, _translate("MainWindow", "1.0"))
        __sortingEnabled = self.listWidget_allergies_before.isSortingEnabled()
        self.listWidget_allergies_before.setSortingEnabled(False)
        item = self.listWidget_allergies_before.item(0)
        item.setText(_translate("MainWindow", "(List of common food allergies)"))
        item = self.listWidget_allergies_before.item(1)
        item.setText(_translate("MainWindow", "Milk (mostly in children)"))
        item = self.listWidget_allergies_before.item(2)
        item.setText(_translate("MainWindow", "Eggs"))
        item = self.listWidget_allergies_before.item(3)
        item.setText(_translate("MainWindow", "Peanuts"))
        item = self.listWidget_allergies_before.item(4)
        item.setText(_translate("MainWindow", "Tree nuts, like walnuts, almonds, pine nuts, brazil nuts, and pecans."))
        item = self.listWidget_allergies_before.item(5)
        item.setText(_translate("MainWindow", "Soy"))
        item = self.listWidget_allergies_before.item(6)
        item.setText(_translate("MainWindow", "Wheat and other grains with gluten, including barley, rye, and oats."))
        item = self.listWidget_allergies_before.item(7)
        item.setText(_translate("MainWindow", "Fish (mostly in adults)"))
        item = self.listWidget_allergies_before.item(8)
        item.setText(_translate("MainWindow", "Shellfish (mostly in adults)"))
        self.listWidget_allergies_before.setSortingEnabled(__sortingEnabled)
        self.pushButton_allergies_delete.setText(_translate("MainWindow", "<< Delete"))
        self.pushButton_allergies_add.setText(_translate("MainWindow", "Add >>"))
        self.label_10.setText(_translate("MainWindow", "# of minutes of exercise"))
        self.label_16.setText(_translate("MainWindow", "%"))
        self.label_17.setText(_translate("MainWindow", "Body Fat"))
        self.comboBox_fitnessgoal.setItemText(0, _translate("MainWindow", "What are your fitness goal?"))
        self.comboBox_fitnessgoal.setItemText(1, _translate("MainWindow", "1) lose weight"))
        self.comboBox_fitnessgoal.setItemText(2, _translate("MainWindow", "2) maintain"))
        self.comboBox_fitnessgoal.setItemText(3, _translate("MainWindow", "3) gain muscle"))
        self.comboBox_fitnessgoal.setItemText(4, _translate("MainWindow", "4) endurance"))
        self.comboBox_typeofexercise.setItemText(0, _translate("MainWindow", "What type of exercise?"))
        self.comboBox_typeofexercise.setItemText(1, _translate("MainWindow", "a) none"))
        self.comboBox_typeofexercise.setItemText(2, _translate("MainWindow", "b) light"))
        self.comboBox_typeofexercise.setItemText(3, _translate("MainWindow", "c) moderate"))
        self.comboBox_typeofexercise.setItemText(4, _translate("MainWindow", "d) vigorous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

